# Generated by Django 4.1.5 on 2023-01-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoTask', '0002_remove_task_task_endtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.CharField(default='Not Completed', max_length=20),
        ),
    ]
